# Generated by Django 3.2.5 on 2023-05-06 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_auto_20230506_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dream_detail', models.CharField(max_length=400)),
                ('emotion_during_detail', models.CharField(max_length=400)),
                ('emotion_waking_detail', models.CharField(max_length=400)),
                ('event_related_detail', models.CharField(max_length=400)),
                ('dream_symbolize_detail', models.CharField(max_length=400)),
                ('similar_dream_detail', models.CharField(max_length=400)),
                ('prediction_option', models.CharField(default=None, max_length=20)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile')),
            ],
        ),
    ]
